version: 2.1
orbs:
      docker: circleci/docker@0.5.20
jobs:
    build_and_test:
        working_directory: ~
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run:
                  name: update-npm
                  command: 'sudo npm install -g npm@latest'
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: install-npm
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: formatting-check
                  command: npx prettier -c **
            - run:
                  name: static-analysis
                  command: npm run lint
            - run:
                  name: test
                  command: npm test
workflows:
      version: 2
      build_test_push:
            jobs:
                  - build_and_test
                  - docker/publish:
                        image: leonpatmore/spammer-v2
                        tag: ${CIRCLE_SHA1}
